# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-06 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Super Admin'), (1, 'Site User'), (2, 'Site Admin')], default=1)),
                ('sites', models.ManyToManyField(to='system.Site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bibos_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
